import { useForm } from "react-hook-form";
import { BatteryMotorData } from "../../services/robotsService";
import { Button } from "@/components/ui/Button";
import { Battery, Cog } from "lucide-react";

type BatteryMotorDataFormProps = {
    initialData?: BatteryMotorData;
    onSubmit: (data: BatteryMotorData) => void;
    isLoading: boolean;
    onCancel?: () => void;
};

const BatteryMotorDataForm = ({
    initialData,
    onSubmit,
    isLoading,
    onCancel
}: BatteryMotorDataFormProps) => {
    const {
        register,
        handleSubmit,
        formState: { errors, isDirty }
    } = useForm<BatteryMotorData>({
        defaultValues: initialData || {}
    });

    return (
        <form
            onSubmit={handleSubmit(onSubmit)}
            className="space-y-6 rounded-lg bg-slate-800/30 p-6"
        >
            {/* Battery Section */}
            <div className="space-y-6">
                {/* Battery Header */}
                <div className="flex items-center gap-3 border-b border-gray-700 pb-4">
                    {/* <Battery className="h-6 w-6 text-green-400" /> */}
                    <h3 className="text-xl font-bold text-white">
                        Battery Information
                    </h3>
                </div>

                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                    {/* Battery ID (Autogenerated) */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Battery ID
                        </label>
                        <input
                            type="text"
                            {...register("batteryId")}
                            className="w-full rounded-md border border-gray-600 bg-slate-700/50 px-4 py-2.5 text-gray-400 outline-none"
                            placeholder="BAT001 (autogenerated)"
                            readOnly
                            disabled
                        />
                        <p className="mt-1.5 text-xs text-gray-400">
                            Format: BAT&lt;sequence&gt; - Auto-generated
                        </p>
                    </div>

                    {/* Battery Code */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Battery Code
                        </label>
                        <input
                            type="text"
                            {...register("batteryCode", { maxLength: 100 })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="Generated by Flo Mobility"
                        />
                    </div>

                    {/* Battery Serial Number */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Battery Serial Number
                        </label>
                        <input
                            type="text"
                            {...register("batterySerialNo", { maxLength: 100 })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="As typed on battery tag"
                        />
                    </div>

                    {/* Battery Type */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Battery Type
                        </label>
                        <input
                            type="text"
                            {...register("batteryType", { maxLength: 200 })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="e.g., Micronix LFP, Inverted LFP"
                        />
                        <p className="mt-1.5 text-xs text-gray-400">
                            Include make, model, and vendor
                        </p>
                    </div>

                    {/* Bluetooth Connection Serial Number */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Bluetooth Serial Number
                        </label>
                        <input
                            type="text"
                            {...register("bluetoothConnectionSerialNo", {
                                maxLength: 100
                            })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="Observed from Bluetooth"
                        />
                    </div>

                    {/* Battery ID Dropdown */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Battery Selection
                        </label>
                        <input
                            type="text"
                            {...register("batteryIdDropdown", {
                                maxLength: 100
                            })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="Select from battery code field"
                        />
                        <p className="mt-1.5 text-xs text-gray-400">
                            Dropdown from battery code field
                        </p>
                    </div>

                    {/* Flo Stack ID */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Flo Stack ID
                        </label>
                        <input
                            type="text"
                            {...register("floStackId", { maxLength: 100 })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="Flo stack identifier"
                        />
                    </div>
                </div>
            </div>

            {/* Motor Section */}
            <div className="space-y-6">
                {/* Motor Header */}
                <div className="flex items-center gap-3 border-b border-gray-700 pb-4">
                    {/* <Cog className="h-6 w-6 text-orange-400" /> */}
                    <h3 className="text-xl font-bold text-white">
                        Motor Information
                    </h3>
                </div>

                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                    {/* Motor Type */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Motor Type
                        </label>
                        <select
                            {...register("motorType")}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                        >
                            <option value="">Select Motor Type</option>
                            <option value="Brushed DC">Brushed DC</option>
                            <option value="Brushless DC">Brushless DC</option>
                            <option value="Stepper">Stepper Motor</option>
                            <option value="Servo">Servo Motor</option>
                            <option value="AC Induction">AC Induction</option>
                        </select>
                    </div>

                    {/* Motor Model */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Motor Model
                        </label>
                        <input
                            type="text"
                            {...register("motorModel", { maxLength: 100 })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="e.g., XYZ-500, ABC-1000"
                        />
                    </div>

                    {/* Motor Serial Number */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Motor Serial Number
                        </label>
                        <input
                            type="text"
                            {...register("motorSerialNumber", {
                                maxLength: 100
                            })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="Motor serial number"
                        />
                    </div>

                    {/* Motor ID */}
                    <div>
                        <label className="mb-2 block text-sm font-semibold text-gray-200">
                            Motor ID
                        </label>
                        <input
                            type="text"
                            {...register("motorId", { maxLength: 100 })}
                            className="w-full rounded-md border border-gray-600 bg-slate-900/70 px-4 py-2.5 text-white placeholder-gray-400 outline-none transition-all focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                            placeholder="Motor identifier"
                        />
                    </div>
                </div>
            </div>

            {/* Action Buttons */}
            <div className="flex justify-end gap-3 border-t border-gray-700 pt-6">
                {onCancel && (
                    <Button
                        type="button"
                        onClick={onCancel}
                        className="rounded-md border border-gray-600 bg-transparent px-6 py-2.5 text-white transition-all hover:bg-gray-700/50"
                    >
                        Cancel
                    </Button>
                )}
                <Button
                    type="submit"
                    disabled={isLoading || !isDirty}
                    className="rounded-md bg-gradient-to-r from-blue-600 to-blue-500 px-8 py-2.5 font-semibold text-white shadow-lg shadow-blue-500/30 transition-all hover:from-blue-500 hover:to-blue-400 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none"
                >
                    {isLoading ? (
                        <span className="flex items-center gap-2">
                            <svg
                                className="h-5 w-5 animate-spin"
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                            >
                                <circle
                                    className="opacity-25"
                                    cx="12"
                                    cy="12"
                                    r="10"
                                    stroke="currentColor"
                                    strokeWidth="4"
                                ></circle>
                                <path
                                    className="opacity-75"
                                    fill="currentColor"
                                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                                ></path>
                            </svg>
                            Saving...
                        </span>
                    ) : (
                        "Save Changes"
                    )}
                </Button>
            </div>
        </form>
    );
};

export default BatteryMotorDataForm;
